### PR TITLE
Added Ounces to Mass

### PR DESCRIPTION
**Pull request by maherkassim**
Straightforward addition of Ounces to Mass Units

### CODE REVIEW

**Comment by anjdreas** [comment]
Other than that, looks good to me. Let me know when you've updated the pull request and I'll merge it in. I don't seem to be notified of new commits in a PR.

Thanks!

**Comment by maherkassim** [comment]
Corrected the whitespace and rearranged the tests alphabetically. Thanks

**Comment by anjdreas** [comment]
That was fast :+1:

**Comment by anjdreas** [comment]
I'll try to release a nuget later today.

**Comment by maherkassim** [comment]
Thank you

**Comment by anjdreas** [comment]
Nuget 3.6.0 is now out.

**Pull request merged**
