### PR TITLE
Feature/add flow units

### PR DESCRIPTION
**Pull request by jcramer**
Andreas, Per my email, I would like to add flow units for MGD and ft3/sec which are common US Customary Units. Thank you,  Jim

### CODE REVIEW

**Comment by anjdreas** [comment]
I just fixed the script on develop. Please rebase this feature branch onto develop and squash to a single commit. There should no longer be a need to manually modify any of the g.cs generated files.

**Comment by jcramer** [comment]
Rebase / squash complete. I also reverted the generated FlowTestsBase.g.cs code back to it's original state.

**Comment by anjdreas** [comment]
Looks good, thanks! Will release a new nuget shortly.

**Comment by anjdreas** [comment]
3.4.0-alpha2 is now out with this change, I need some feedback on changes related to PCL profiles and Xamarin before I can push to stable.

**Comment by anjdreas** [comment]
3.4.0 is now out.

**Pull request merged**
