### PR TITLE
Added Stone to Mass

### PR DESCRIPTION
**Pull request by mperdeck**
Added Stone to Mass. Stone is customarily used in the UK when people give their body weight. See for example 
https://www.newme.co.uk/#calculator-start

### CODE REVIEW

**Comment by anjdreas** [comment]
Great work!
Strictly speaking, adding the Stone unit and adding the two combo extensions should be two separate pull requests, but that's fine. At least keep them as two separate commits, as you already have now. 

 When you're done, please squash the typo commit and any further fix commits and rebase onto latest develop, then add a comment so I'm notified by email to check it out.

Thanks

**Comment by anjdreas** [comment]
Still need to fix that tolerance for this test:

Test(s) failed.   Expected: 14.061353110000002d +/- 1.0000000000000001E-05d
  But was:  14.06136347d

   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.AssertDoublesAreEqual(Double expected, Double actual, Double delta, String message, Object[] args)
   at NUnit.Framework.Assert.AreEqual(Double expected, Double actual, Double delta)
   at UnitsNet.Tests.CustomCode.StonePoundsTests.StonePoundsFrom() in f:\BuildAgent\work\73aabaa30e644e74\Tests\CustomCode\StonePoundsTests.cs:line 27



Other than that, this is looking good now. Can you squash the fix commits so we get a clean pull request before I merge it in?

**Comment by anjdreas** [comment]
Some ToString() tests are failing:

http://dev.swingcatalyst.com/TeamCity/viewLog.html?buildId=21834&buildTypeId=UnitsNet

**Comment by anjdreas** [comment]
1 test still failing, on tolerance:

Test(s) failed.   Expected: 14.061353110000002d +/- 1.0000000000000001E-05d
  But was:  14.06136347d

   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.AssertDoublesAreEqual(Double expected, Double actual, Double delta, String message, Object[] args)
   at NUnit.Framework.Assert.AreEqual(Double expected, Double actual, Double delta)
   at UnitsNet.Tests.CustomCode.StonePoundsTests.StonePoundsFrom() in f:\BuildAgent\work\73aabaa30e644e74\Tests\CustomCode\StonePoundsTests.cs:line 27

**Comment by anjdreas** [comment]
Awesome, now to clean up this PR. Squash all the fix commits so you're left with 2-3 meaningful commits. Also make sure it's rebased on top of latest develop branch.

**Comment by mperdeck** [comment]
Not sure how to do this. I'm pretty new to Git (using Github for Windows). Or maybe it's because it is now 11:30 at night here (I'm in Sydney, Australia) and my brain is kind off fried. Need to go to work early tomorrow. 

Is the cleaning up critical? Or would it be ok to leave it like this for now? Alternatively, would you be able and willing to fix this at your end please? That might save some toing and froing and would wrap up this story.

**Comment by anjdreas** [comment]
Alright. I'll merge it in as-is. If I were to rebase on your behalf I think I might be credited for your work.

I'm not familiar with Github for Windows either, so if you are using GUI instead of git commands then I can't help you. I recommend brushing up on this though, it's an essential workflow in git and often a requirement for pull requests on open source projects in order to keep the log tidy and readable.

Thanks a bunch for your effort, these were good additions to the project!

**Comment by anjdreas** [comment]
Nuget 3.8.0 out.

**Pull request merged**
